/// This file is automatically generated. Do not change, modifications will be overwritten.

#pragma once

#include "interface/cInterfaceWindowXML.h"
#include "cGameWindow.h"
#include <memory>

namespace screens {

    class cChoiceBoxBase : public cInterfaceWindowXML 
    {
        public:
            cChoiceBoxBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
    
    };

    class cLoadMenuBase : public cInterfaceWindowXML 
    {
        public:
            cLoadMenuBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_Background_id      = -1;
            int m_FileName_id        = -1;
            int m_LoadGame_id        = -1;
            int m_WhoreMaster_id     = -1;
    };

    class cNewGameBase : public cInterfaceWindowXML 
    {
        public:
            cNewGameBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Background_id      = -1;
            int m_BrothelName_id     = -1;
            int m_Cancel_id          = -1;
            int m_Config_id          = -1;
            int m_Label1_id          = -1;
            int m_Label2_id          = -1;
            int m_Label3_id          = -1;
            int m_Label4_id          = -1;
            int m_Label5_id          = -1;
            int m_Ok_id              = -1;
            int m_PlayerBirthDayNum_id = -1;
            int m_PlayerBirthDay_id  = -1;
            int m_PlayerBirthMonthNum_id = -1;
            int m_PlayerBirthMonth_id = -1;
            int m_PlayerHoroscope_id = -1;
            int m_PlayerName_id      = -1;
            int m_PlayerSurname_id   = -1;
            int m_WhoreMaster_id     = -1;
    };

    class cTransferGirlsBase : public cGameWindow 
    {
        public:
            cTransferGirlsBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_BrothelLeft_id     = -1;
            int m_BrothelRight_id    = -1;
            int m_LabelLeft_id       = -1;
            int m_LabelRight_id      = -1;
            int m_ListLeft_id        = -1;
            int m_ListRight_id       = -1;
            int m_ShiftLeft_id       = -1;
            int m_ShiftRight_id      = -1;
    };

    class cTurnSummaryBase : public cInterfaceWindowXML 
    {
        public:
            cTurnSummaryBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_Background_id      = -1;
            int m_Category_id        = -1;
            int m_CurrentBrothel_id  = -1;
            int m_Event_id           = -1;
            int m_GoTo_id            = -1;
            int m_Item_id            = -1;
            int m_LabelDesc_id       = -1;
            int m_LabelEvent_id      = -1;
            int m_LabelItem_id       = -1;
            int m_NextBtn_id         = -1;
            int m_NextWeek_id        = -1;
            int m_PrevBtn_id         = -1;
    };

    class cBankScreenBase : public cInterfaceWindowXML 
    {
        public:
            cBankScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_BankDetails_id     = -1;
            int m_BankIcon_id        = -1;
            int m_DepositAllBtn_id   = -1;
            int m_DepositBtn_id      = -1;
            int m_ScreenHeader_id    = -1;
            int m_WithdrawAllBtn_id  = -1;
            int m_WithdrawBtn_id     = -1;
    };

    class cBuildingBaseBase : public cInterfaceWindowXML 
    {
        public:
            cBuildingBaseBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Background_id      = -1;
            int m_BuildingDetails_id = -1;
            int m_BuildingLabel_id   = -1;
            int m_GirlImage_id       = -1;
            int m_GirlManagement_id  = -1;
            int m_Menu_id            = -1;
            int m_NextBtn_id         = -1;
            int m_NextWeek_id        = -1;
            int m_PrevBtn_id         = -1;
            int m_Setup_id           = -1;
            int m_VisitTown_id       = -1;
            int m_YourOffice_id      = -1;
    };

    class cBuildingSetupScreenBase : public cGameWindow 
    {
        public:
            cBuildingSetupScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_10PotionsBtn_id    = -1;
            int m_20PotionsBtn_id    = -1;
            int m_AdvertisingSlider_id = -1;
            int m_AdvertisingValue_id = -1;
            int m_AutoBuyPotionToggle_id = -1;
            int m_AvailablePotions_id = -1;
            int m_BackBtn_id         = -1;
            int m_BuildRoomsBtn_id   = -1;
            int m_CurrentBrothel_id  = -1;
            int m_Gold_id            = -1;
            int m_PotionCost_id      = -1;
            int m_ProhibitAnalToggle_id = -1;
            int m_ProhibitBdsmtoggle_id = -1;
            int m_ProhibitBeastToggle_id = -1;
            int m_ProhibitFootJobToggle_id = -1;
            int m_ProhibitGroupToggle_id = -1;
            int m_ProhibitHandJobToggle_id = -1;
            int m_ProhibitLesbianToggle_id = -1;
            int m_ProhibitNormalToggle_id = -1;
            int m_ProhibitOralToggle_id = -1;
            int m_ProhibitStripToggle_id = -1;
            int m_ProhibitTittyToggle_id = -1;
            int m_RoomAddCost_id     = -1;
            int m_SexRestrictions_id = -1;
    };

    class cClinictryScreenBase : public cInterfaceWindowXML 
    {
        public:
            cClinictryScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_Clinic2_id         = -1;
            int m_WalkBtn_id         = -1;
    };

    class cDungeonScreenBase : public cGameWindow 
    {
        public:
            cDungeonScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_AllowFoodBtn_id    = -1;
            int m_Arena_id           = -1;
            int m_BackBtn_id         = -1;
            int m_BrandSlaveBtn_id   = -1;
            int m_Brothel0_id        = -1;
            int m_Brothel1_id        = -1;
            int m_Brothel2_id        = -1;
            int m_Brothel3_id        = -1;
            int m_Brothel4_id        = -1;
            int m_Brothel5_id        = -1;
            int m_Brothel6_id        = -1;
            int m_Centre_id          = -1;
            int m_Clinic_id          = -1;
            int m_DetailsBtn_id      = -1;
            int m_DungeonHeader_id   = -1;
            int m_Farm_id            = -1;
            int m_GirlImage_id       = -1;
            int m_GirlList_id        = -1;
            int m_Gold_id            = -1;
            int m_House_id           = -1;
            int m_InteractBtn_id     = -1;
            int m_InteractCount_id   = -1;
            int m_ReleaseBtn_id      = -1;
            int m_ReleaseTo_id       = -1;
            int m_RoomsFree_id       = -1;
            int m_SelectAllCust_id   = -1;
            int m_SelectAllGirls_id  = -1;
            int m_SellBtn_id         = -1;
            int m_StopFeedingBtn_id  = -1;
            int m_Studio_id          = -1;
            int m_TortureBtn_id      = -1;
    };

    class cGalleryScreenBase : public cGameWindow 
    {
        public:
            cGalleryScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_Futa_id            = -1;
            int m_GirlImage_id       = -1;
            int m_ImageData_id       = -1;
            int m_ImageList_id       = -1;
            int m_ImageName_id       = -1;
            int m_ImageSource_id     = -1;
            int m_NextBtn_id         = -1;
            int m_Participants_id    = -1;
            int m_Pregnant_id        = -1;
            int m_PrevBtn_id         = -1;
            int m_TiedUp_id          = -1;
    };

    class cGameSetupBase : public cInterfaceWindowXML 
    {
        public:
            cGameSetupBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_LoadBtn_id         = -1;
            int m_OkBtn_id           = -1;
            int m_RevertBtn_id       = -1;
            int m_ScreenHeader_id    = -1;
            int m_SettingsList_id    = -1;
    };

    class cGangsScreenBase : public cInterfaceWindowXML 
    {
        public:
            cGangsScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_AutoBuyHealToggle_id = -1;
            int m_AutoBuyNetsToggle_id = -1;
            int m_BackBtn_id         = -1;
            int m_BuyHealPotBtn10_id = -1;
            int m_BuyHealPotBtn20_id = -1;
            int m_BuyHealPotBtn_id   = -1;
            int m_BuyNetsBtn10_id    = -1;
            int m_BuyNetsBtn20_id    = -1;
            int m_BuyNetsBtn_id      = -1;
            int m_Catacombs_id       = -1;
            int m_ControlCatacombs_id = -1;
            int m_FireArrow_id       = -1;
            int m_GangFireBtn_id     = -1;
            int m_GangGetsBeast_id   = -1;
            int m_GangGetsGirls_id   = -1;
            int m_GangGetsItems_id   = -1;
            int m_GangHireBtn_id     = -1;
            int m_GangList_id        = -1;
            int m_GirlsPercSlider_id = -1;
            int m_Gold_id            = -1;
            int m_HealPotDescription_id = -1;
            int m_HireArrow_id       = -1;
            int m_ItemsPercSlider_id = -1;
            int m_MissionDescription_id = -1;
            int m_MissionList_id     = -1;
            int m_NetDescription_id  = -1;
            int m_RecruitList_id     = -1;
            int m_TotalCost_id       = -1;
            int m_TxtControlledGangs_id = -1;
            int m_TxtMissions_id     = -1;
            int m_WeaponDescription_id = -1;
            int m_WeaponUpBtn_id     = -1;
    };

    class cGetInputBase : public cInterfaceWindowXML 
    {
        public:
            cGetInputBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Cancel_id          = -1;
            int m_Label_id           = -1;
            int m_Ok_id              = -1;
            int m_TextField_id       = -1;
    };

    class cGirlDetailsScreenBase : public cGameWindow 
    {
        public:
            cGirlDetailsScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_AccomSlider_id     = -1;
            int m_AccomValue_id      = -1;
            int m_BackBtn_id         = -1;
            int m_DayBtn_id          = -1;
            int m_GalleryBtn_id      = -1;
            int m_GirlDescription_id = -1;
            int m_GirlImage_id       = -1;
            int m_GirlName_id        = -1;
            int m_HousePercSlider_id = -1;
            int m_HousePercValue_id  = -1;
            int m_InteractBtn_id     = -1;
            int m_InteractCount_id   = -1;
            int m_InventoryBtn_id    = -1;
            int m_JobHeader_id       = -1;
            int m_JobList_id         = -1;
            int m_JobTypeHeader_id   = -1;
            int m_JobTypeList_id     = -1;
            int m_MoreBtn_id         = -1;
            int m_NextBtn_id         = -1;
            int m_NightBtn_id        = -1;
            int m_PrevBtn_id         = -1;
            int m_ReleaseDungeonBtn_id = -1;
            int m_SendDungeonBtn_id  = -1;
            int m_TakeGoldBtn_id     = -1;
            int m_TraitDescription_id = -1;
            int m_TraitHeader_id     = -1;
            int m_TraitInfoBtn_id    = -1;
            int m_TraitList_id       = -1;
            int m_UseAntiPregToggle_id = -1;
    };

    class cGirlManagementBaseBase : public cInterfaceWindowXML 
    {
        public:
            cGirlManagementBaseBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_CurrentBrothel_id  = -1;
            int m_DayBtn_id          = -1;
            int m_FireBtn_id         = -1;
            int m_FreeSlaveBtn_id    = -1;
            int m_GirlDescription_id = -1;
            int m_GirlImage_id       = -1;
            int m_Gold_id            = -1;
            int m_JobDescription_id  = -1;
            int m_JobHeader_id       = -1;
            int m_JobList_id         = -1;
            int m_JobTypeDescription_id = -1;
            int m_JobTypeHeader_id   = -1;
            int m_JobTypeList_id     = -1;
            int m_NextBtn_id         = -1;
            int m_NextWeek_id        = -1;
            int m_NightBtn_id        = -1;
            int m_PrevBtn_id         = -1;
            int m_SellSlaveBtn_id    = -1;
            int m_TransferBtn_id     = -1;
            int m_ViewDetailsBtn_id  = -1;
    };

    class cInGameMenuBase : public cInterfaceWindowXML 
    {
        public:
            cInGameMenuBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_ContinueBtn_id     = -1;
            int m_QuitBtn_id         = -1;
            int m_SaveBtn_id         = -1;
    };

    class cInfoTraitsScreenBase : public cInterfaceWindowXML 
    {
        public:
            cInfoTraitsScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_DescrTxt_id        = -1;
            int m_Description_id     = -1;
            int m_EffectsList_id     = -1;
            int m_ExclusionList_id   = -1;
            int m_ExclusionsTxt_id   = -1;
            int m_HelpLbl_id         = -1;
            int m_HelpText_id        = -1;
            int m_PropExplLbl_id     = -1;
            int m_PropExplanation_id = -1;
            int m_PropertyList_id    = -1;
            int m_TraitEffectTxt_id  = -1;
            int m_TraitPropTxt_id    = -1;
            int m_TraitsListTxt_id   = -1;
            int m_TraitsList_id      = -1;
    };

    class cItemmanagementScreenBase : public cInterfaceWindowXML 
    {
        public:
            cItemmanagementScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_AutoUseItems_id    = -1;
            int m_BackBtn_id         = -1;
            int m_Buy10LeftBtn_id    = -1;
            int m_Buy10RightBtn_id   = -1;
            int m_CurrentBrothel_id  = -1;
            int m_EquipLeftBtn_id    = -1;
            int m_EquipRightBtn_id   = -1;
            int m_FilterList_id      = -1;
            int m_IndicateLeft_id    = -1;
            int m_IndicateRight_id   = -1;
            int m_ItemDesc_id        = -1;
            int m_ItemsLeftHeader_id = -1;
            int m_ItemsLeftList_id   = -1;
            int m_ItemsRightHeader_id = -1;
            int m_ItemsRightList_id  = -1;
            int m_OwnersLeftDetails_id = -1;
            int m_OwnersLeftHeader_id = -1;
            int m_OwnersLeftList_id  = -1;
            int m_OwnersRightDetails_id = -1;
            int m_OwnersRightHeader_id = -1;
            int m_OwnersRightList_id = -1;
            int m_PlayerGold_id      = -1;
            int m_Sell10LeftBtn_id   = -1;
            int m_Sell10RightBtn_id  = -1;
            int m_SellAllLeftBtn_id  = -1;
            int m_SellAllRightBtn_id = -1;
            int m_ShiftHeader_id     = -1;
            int m_ShiftLeftBtn_id    = -1;
            int m_ShiftRightBtn_id   = -1;
            int m_UnequipLeftBtn_id  = -1;
            int m_UnequipRightBtn_id = -1;
    };

    class cMainMenuBase : public cInterfaceWindowXML 
    {
        public:
            cMainMenuBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Background_id      = -1;
            int m_Continue_id        = -1;
            int m_LoadGame_id        = -1;
            int m_NewGame_id         = -1;
            int m_QuitGame_id        = -1;
            int m_ReadMe_id          = -1;
            int m_Settings_id        = -1;
            int m_Version_id         = -1;
            int m_VisitUs_id         = -1;
            int m_WhoreMaster_id     = -1;
    };

    class cMayorScreenBase : public cInterfaceWindowXML 
    {
        public:
            cMayorScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_BribeBtn_id        = -1;
            int m_MayorDetails_id    = -1;
            int m_MayorIcon_id       = -1;
            int m_ScreenHeader_id    = -1;
    };

    class cMovieMakerScreenBase : public cInterfaceWindowXML 
    {
        public:
            cMovieMakerScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_AddScene_id        = -1;
            int m_AutoCreateMovies_id = -1;
            int m_BackBtn_id         = -1;
            int m_MakeThisMovie_id   = -1;
            int m_MarketResearch_id  = -1;
            int m_MovieDetailTxt_id  = -1;
            int m_MovieDetails_id    = -1;
            int m_MovieNameTxt_id    = -1;
            int m_MovieName_id       = -1;
            int m_Movie_id           = -1;
            int m_PredictedAudience_id = -1;
            int m_Prediction_id      = -1;
            int m_ReleaseMovieBtn_id = -1;
            int m_RemoveScene_id     = -1;
            int m_ScenesList_id      = -1;
            int m_Scenes_id          = -1;
            int m_ScrapScene_id      = -1;
    };

    class cMovieMarketScreenBase : public cInterfaceWindowXML 
    {
        public:
            cMovieMarketScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_AdCampaign_id      = -1;
            int m_BackBtn_id         = -1;
            int m_DecreaseTicketPrice_id = -1;
            int m_GroupsList_id      = -1;
            int m_IncreaseTicketPrice_id = -1;
            int m_MovieTxt_id        = -1;
            int m_MoviesList_id      = -1;
            int m_PredictionList_id  = -1;
            int m_Prediction_id      = -1;
            int m_PromoTxt_id        = -1;
            int m_SurveyTxt_id       = -1;
            int m_Survey_id          = -1;
            int m_TargetGroups_id    = -1;
            int m_TicketPriceTxt_id  = -1;
    };

    class cPlayerOfficeScreenBase : public cGameWindow 
    {
        public:
            cPlayerOfficeScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Background_id      = -1;
            int m_BuildingList_id    = -1;
            int m_BuyInteract10_id   = -1;
            int m_BuyInteract_id     = -1;
            int m_D_id               = -1;
            int m_DateLbl_id         = -1;
            int m_Dungeon_id         = -1;
            int m_GangManagement_id  = -1;
            int m_InfoLbl_id         = -1;
            int m_InteractText_id    = -1;
            int m_InventoryBtn_id    = -1;
            int m_Menu_id            = -1;
            int m_NextWeek_id        = -1;
            int m_Settings_id        = -1;
            int m_TurnSummary_id     = -1;
            int m_VisitBuildings_id  = -1;
            int m_VisitTown_id       = -1;
    };

    class cPopupMessageBase : public cInterfaceWindowXML 
    {
        public:
            cPopupMessageBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
    
    };

    class cPreparingGameScreenBase : public cGameWindow 
    {
        public:
            cPreparingGameScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_Background_id      = -1;
            int m_Text1_id           = -1;
            int m_Text2_id           = -1;
            int m_Text3_id           = -1;
    };

    class cPrisonScreenBase : public cGameWindow 
    {
        public:
            cPrisonScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_GirlDescription_id = -1;
            int m_PrisonIcon_id      = -1;
            int m_PrisonList_id      = -1;
            int m_ReleaseBtn_id      = -1;
            int m_ScreenHeader_id    = -1;
            int m_ShowMoreBtn_id     = -1;
    };

    class cPropertyManagementBase : public cInterfaceWindowXML 
    {
        public:
            cPropertyManagementBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_PArName_id         = -1;
            int m_PB0AdvAmnt_id      = -1;
            int m_PB0AdvSlid_id      = -1;
            int m_PB0Name_id         = -1;
            int m_PB0NoAnal_id       = -1;
            int m_PB0NoBdsm_id       = -1;
            int m_PB0NoBeast_id      = -1;
            int m_PB0NoGroup_id      = -1;
            int m_PB0NoHandJob_id    = -1;
            int m_PB0NoLes_id        = -1;
            int m_PB0NoNorm_id       = -1;
            int m_PB0NoOral_id       = -1;
            int m_PB0NoTitty_id      = -1;
            int m_PB0PotA_id         = -1;
            int m_PB0PotB_id         = -1;
            int m_PB1AdvAmnt_id      = -1;
            int m_PB1AdvSlid_id      = -1;
            int m_PB1Name_id         = -1;
            int m_PB1NoAnal_id       = -1;
            int m_PB1NoBdsm_id       = -1;
            int m_PB1NoBeast_id      = -1;
            int m_PB1NoGroup_id      = -1;
            int m_PB1NoHandJob_id    = -1;
            int m_PB1NoLes_id        = -1;
            int m_PB1NoNorm_id       = -1;
            int m_PB1NoOral_id       = -1;
            int m_PB1NoTitty_id      = -1;
            int m_PB1PotA_id         = -1;
            int m_PB1PotB_id         = -1;
            int m_PB2AdvAmnt_id      = -1;
            int m_PB2AdvSlid_id      = -1;
            int m_PB2Name_id         = -1;
            int m_PB2NoAnal_id       = -1;
            int m_PB2NoBdsm_id       = -1;
            int m_PB2NoBeast_id      = -1;
            int m_PB2NoGroup_id      = -1;
            int m_PB2NoHandJob_id    = -1;
            int m_PB2NoLes_id        = -1;
            int m_PB2NoNorm_id       = -1;
            int m_PB2NoOral_id       = -1;
            int m_PB2NoTitty_id      = -1;
            int m_PB2PotA_id         = -1;
            int m_PB2PotB_id         = -1;
            int m_PB3AdvAmnt_id      = -1;
            int m_PB3AdvSlid_id      = -1;
            int m_PB3Name_id         = -1;
            int m_PB3NoAnal_id       = -1;
            int m_PB3NoBdsm_id       = -1;
            int m_PB3NoBeast_id      = -1;
            int m_PB3NoGroup_id      = -1;
            int m_PB3NoHandJob_id    = -1;
            int m_PB3NoLes_id        = -1;
            int m_PB3NoNorm_id       = -1;
            int m_PB3NoOral_id       = -1;
            int m_PB3NoTitty_id      = -1;
            int m_PB3PotA_id         = -1;
            int m_PB3PotB_id         = -1;
            int m_PB4AdvAmnt_id      = -1;
            int m_PB4AdvSlid_id      = -1;
            int m_PB4Name_id         = -1;
            int m_PB4NoAnal_id       = -1;
            int m_PB4NoBdsm_id       = -1;
            int m_PB4NoBeast_id      = -1;
            int m_PB4NoGroup_id      = -1;
            int m_PB4NoHandJob_id    = -1;
            int m_PB4NoLes_id        = -1;
            int m_PB4NoNorm_id       = -1;
            int m_PB4NoOral_id       = -1;
            int m_PB4NoTitty_id      = -1;
            int m_PB4PotA_id         = -1;
            int m_PB4PotB_id         = -1;
            int m_PB5AdvAmnt_id      = -1;
            int m_PB5AdvSlid_id      = -1;
            int m_PB5Name_id         = -1;
            int m_PB5NoAnal_id       = -1;
            int m_PB5NoBdsm_id       = -1;
            int m_PB5NoBeast_id      = -1;
            int m_PB5NoGroup_id      = -1;
            int m_PB5NoHandJob_id    = -1;
            int m_PB5NoLes_id        = -1;
            int m_PB5NoNorm_id       = -1;
            int m_PB5NoOral_id       = -1;
            int m_PB5NoTitty_id      = -1;
            int m_PB5PotA_id         = -1;
            int m_PB5PotB_id         = -1;
            int m_PB6AdvAmnt_id      = -1;
            int m_PB6AdvSlid_id      = -1;
            int m_PB6Name_id         = -1;
            int m_PB6NoAnal_id       = -1;
            int m_PB6NoBdsm_id       = -1;
            int m_PB6NoBeast_id      = -1;
            int m_PB6NoGroup_id      = -1;
            int m_PB6NoHandJob_id    = -1;
            int m_PB6NoLes_id        = -1;
            int m_PB6NoNorm_id       = -1;
            int m_PB6NoOral_id       = -1;
            int m_PB6NoTitty_id      = -1;
            int m_PB6PotA_id         = -1;
            int m_PB6PotB_id         = -1;
            int m_PCeName_id         = -1;
            int m_PClName_id         = -1;
            int m_PHoAdvAmnt_id      = -1;
            int m_PHoAdvSlid_id      = -1;
            int m_PHoName_id         = -1;
            int m_PHoNoAnal_id       = -1;
            int m_PHoNoBdsm_id       = -1;
            int m_PHoNoBeast_id      = -1;
            int m_PHoNoGroup_id      = -1;
            int m_PHoNoHandJob_id    = -1;
            int m_PHoNoLes_id        = -1;
            int m_PHoNoNorm_id       = -1;
            int m_PHoNoOral_id       = -1;
            int m_PHoNoTitty_id      = -1;
            int m_PHoPotA_id         = -1;
            int m_PHoPotB_id         = -1;
            int m_PStName_id         = -1;
            int m_PotionCost_id      = -1;
    };

    class cSettingsBase : public cInterfaceWindowXML 
    {
        public:
            cSettingsBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_BackBtn_id         = -1;
            int m_CharactersLabel_id = -1;
            int m_Characters_id      = -1;
            int m_DefaultImagesLabel_id = -1;
            int m_DefaultImages_id   = -1;
            int m_DrawingsCb_id      = -1;
            int m_Fullscreen_id      = -1;
            int m_HeightLabel_id     = -1;
            int m_ItemsLabel_id      = -1;
            int m_Items_id           = -1;
            int m_OkBtn_id           = -1;
            int m_PhotosCb_id        = -1;
            int m_PreferDefault_id   = -1;
            int m_RenderingsCb_id    = -1;
            int m_RevertBtn_id       = -1;
            int m_SavesLabel_id      = -1;
            int m_Saves_id           = -1;
            int m_ScreenHeader_id    = -1;
            int m_StyleLabel_id      = -1;
            int m_ThemeLabel_id      = -1;
            int m_ThemeList_id       = -1;
            int m_WidthLabel_id      = -1;
            int m_WindowHeight_id    = -1;
            int m_WindowWidth_id     = -1;
    };

    class cSlavemarketScreenBase : public cGameWindow 
    {
        public:
            cSlavemarketScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Arena_id           = -1;
            int m_BackBtn_id         = -1;
            int m_Brothel0_id        = -1;
            int m_Brothel1_id        = -1;
            int m_Brothel2_id        = -1;
            int m_Brothel3_id        = -1;
            int m_Brothel4_id        = -1;
            int m_Brothel5_id        = -1;
            int m_Brothel6_id        = -1;
            int m_BuySlaveBtn_id     = -1;
            int m_Centre_id          = -1;
            int m_Clinic_id          = -1;
            int m_Dungeon_id         = -1;
            int m_Farm_id            = -1;
            int m_GirlDesc_id        = -1;
            int m_GirlImage_id       = -1;
            int m_Gold_id            = -1;
            int m_House_id           = -1;
            int m_ReleaseTo_id       = -1;
            int m_RoomsFree_id       = -1;
            int m_ShowMoreBtn_id     = -1;
            int m_SlaveDetails_id    = -1;
            int m_SlaveList_id       = -1;
            int m_SlaveMarket_id     = -1;
            int m_Studio_id          = -1;
            int m_TraitListT_id      = -1;
    };

    class cTownScreenBase : public cGameWindow 
    {
        public:
            cTownScreenBase();
            
            static std::shared_ptr<cInterfaceWindow> create();
            
        private:
            void process() override { };
            void set_ids() override;
            
            virtual void setup_callbacks() = 0;
    
        protected:
            int m_Arena_id           = -1;
            int m_BackBtn_id         = -1;
            int m_Bank_id            = -1;
            int m_Brothel0_id        = -1;
            int m_Brothel1_id        = -1;
            int m_Brothel2_id        = -1;
            int m_Brothel3_id        = -1;
            int m_Brothel4_id        = -1;
            int m_Brothel5_id        = -1;
            int m_Brothel6_id        = -1;
            int m_Centre_id          = -1;
            int m_Clinic_id          = -1;
            int m_CurrentBrothel_id  = -1;
            int m_Farm_id            = -1;
            int m_GirlImage_id       = -1;
            int m_House_id           = -1;
            int m_MayorsOffice_id    = -1;
            int m_NextWeek_id        = -1;
            int m_Prison_id          = -1;
            int m_Shop_id            = -1;
            int m_SlaveMarket_id     = -1;
            int m_Studio_id          = -1;
            int m_TownMap_id         = -1;
            int m_WalkBtn_id         = -1;
    };
}
